apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-0
  labels:
    type: local
    app: redis
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-1
  labels:
    type: local
    app: redis
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-2
  labels:
    type: local
    app: redis
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis-2" 