apiVersion: v1
kind: Service
metadata:
  name: vote-frontend
  namespace: voting-system
spec:
  selector:
    app: vote-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-frontend-ingress
  namespace: voting-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "vote.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote-frontend
            port:
              number: 3000 