apiVersion: v1
kind: Namespace
metadata:
  name: voting-system
  labels:
    app: voting-system
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    app: voting-system
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app: voting-system
    environment: production 